// frontend/src/pages/Fabrics.jsx
import { useEffect, useState } from "react";
import { t } from "../i18n";

export default function Fabrics({ api, apiBase, role }) {
  const isAdmin = role === "ADMIN";

  const [items, setItems] = useState([]);

  const [error, setError] = useState("");
  const [info, setInfo] = useState("");

  // Form fields (new real-world fabric fields)
  const [name, setName] = useState("");
  const [color, setColor] = useState("");
  const [widthM, setWidthM] = useState("");
  const [lengthM, setLengthM] = useState("");
  const [fabricType, setFabricType] = useState("");
  const [weave, setWeave] = useState("");
  const [finish, setFinish] = useState("LISO"); // LISO | BORDADO
  const [pricePerMeter, setPricePerMeter] = useState("");

  function resetMessages() {
    setError("");
    setInfo("");
  }

  function showApiError(e) {
    if (!e) return setError(t("ui.error"));

    const d = e.detail;
    const mk = d?.messageKey || d?.detail?.messageKey;
    const params = d?.params || d?.detail?.params || {};

    if (mk) return setError(t(mk, params));
    if (e.status === 403) return setError(t("ui.forbidden"));
    if (typeof d === "string") return setError(d);
    if (d?.detail && typeof d.detail === "string") return setError(d.detail);

    return setError(`${t("ui.error")} ${e.status || ""}`);
  }

  async function loadFabrics() {
    const data = await api.request(`${apiBase}/api/fabrics`);
    setItems(Array.isArray(data) ? data : []);
  }

  async function refresh() {
    resetMessages();
    await Promise.all([loadFabrics()]);
  }

  useEffect(() => {
    refresh().catch((e) => showApiError(e));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function clearForm() {
    setName("");
    setColor("");
    setWidthM("");
    setLengthM("");
    setFabricType("");
    setWeave("");
    setFinish("LISO");
    setPricePerMeter("");
  }

  function toNumberOrNull(v) {
    if (v === "" || v === null || v === undefined) return null;
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  }

  async function createFabric(e) {
    e.preventDefault();
    if (!isAdmin) return;

    resetMessages();

    const nameTrim = (name || "").trim();
    const colorTrim = (color || "").trim();

    if (!nameTrim || !colorTrim) {
      setError(t("ui.validationRequired"));
      return;
    }

    const payload = {
      // backend generates code automatically (0004, 0005, ...)
      name: nameTrim,
      color: colorTrim,
      width_m: toNumberOrNull(widthM),
      length_m: toNumberOrNull(lengthM),
      fabric_type: fabricType.trim() ? fabricType.trim() : null,
      weave: weave.trim() ? weave.trim() : null,
      finish: finish || null,
      price_per_meter: toNumberOrNull(pricePerMeter)
    };

    try {
      await api.request(`${apiBase}/api/fabrics`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });

      setInfo(t("ui.saved"));
      clearForm();
      await loadFabrics();
    } catch (e2) {
      showApiError(e2);
    }
  }

  async function deleteFabric(id) {
    if (!isAdmin) return;

    resetMessages();
    const ok = window.confirm(`${t("ui.confirmDelete")} #${id}?`);
    if (!ok) return;

    try {
      await api.request(`${apiBase}/api/fabrics/${id}`, { method: "DELETE" });
      setInfo(t("ui.deleted"));
      await loadFabrics();
    } catch (e) {
      showApiError(e);
    }
  }

  return (
    <>
      {/* Create */}
      <div className="card">
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "baseline",
            gap: 10,
            flexWrap: "wrap"
          }}
        >
          <div>
            <h2 style={{ margin: 0 }}>{t("ui.createFabric")}</h2>
            <div style={{ color: "var(--muted)", fontSize: 13, marginTop: 4 }}>
              {t("ui.createFabricHint")}
            </div>
          </div>

          <button className="btn" type="button" onClick={() => refresh().catch((e) => showApiError(e))}>
            {t("actions.refresh")}
          </button>
        </div>

        {!isAdmin && (
          <div className="alert alert-warn" style={{ marginTop: 12 }}>
            {t("ui.adminActionsHidden")}
          </div>
        )}

        <form onSubmit={createFabric} style={{ marginTop: 12 }}>
          <div className="grid grid-3">
            <label>
              <div className="label">{t("fields.code")}</div>
              <input value={t("ui.autoGenerated")} disabled />
            </label>

            <label>
              <div className="label">{t("fields.name")}</div>
              <input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Percal 180 hilos" />
            </label>

            <label>
              <div className="label">{t("fields.color")}</div>
              <input value={color} onChange={(e) => setColor(e.target.value)} placeholder="e.g. Blanco" />
            </label>

            <label>
              <div className="label">{t("fields.widthM")}</div>
              <input type="number" step="0.001" value={widthM} onChange={(e) => setWidthM(e.target.value)} />
            </label>

            <label>
              <div className="label">{t("fields.lengthM")}</div>
              <input type="number" step="0.001" value={lengthM} onChange={(e) => setLengthM(e.target.value)} />
            </label>

            <label>
              <div className="label">{t("fields.fabricType")}</div>
              <input value={fabricType} onChange={(e) => setFabricType(e.target.value)} placeholder="e.g. Seda" />
            </label>

            <label>
              <div className="label">{t("fields.weave")}</div>
              <input value={weave} onChange={(e) => setWeave(e.target.value)} placeholder="e.g. Punto" />
            </label>

            <label>
              <div className="label">{t("fields.finish")}</div>
              <select value={finish} onChange={(e) => setFinish(e.target.value)}>
                <option value="LISO">{t("ui.finishPlain")}</option>
                <option value="BORDADO">{t("ui.finishEmbroidered")}</option>
              </select>
            </label>

            <label>
              <div className="label">{t("fields.pricePerMeter")}</div>
              <input
                type="number"
                step="0.01"
                value={pricePerMeter}
                onChange={(e) => setPricePerMeter(e.target.value)}
              />
            </label>

            <div style={{ display: "flex", gap: 10, alignItems: "end" }}>
              <button className="btn btn-primary" type="submit" disabled={!isAdmin}>
                {t("ui.create")}
              </button>
              <button className="btn" type="button" onClick={clearForm}>
                {t("actions.clear")}
              </button>
            </div>
          </div>

          {error && (
            <div className="alert alert-error" style={{ marginTop: 12 }}>
              {error}
            </div>
          )}
          {info && (
            <div className="alert alert-success" style={{ marginTop: 12 }}>
              {info}
            </div>
          )}
        </form>
      </div>

      {/* List */}
      <div className="card">
        <div>
          <h2 style={{ margin: 0 }}>{t("ui.listFabrics")}</h2>
          <div style={{ color: "var(--muted)", fontSize: 13, marginTop: 4 }}>
            {t("ui.listFabricsHint")}
          </div>
        </div>

        <div style={{ marginTop: 12, overflowX: "auto" }}>
          <table className="table">
            <thead>
              <tr>
                <th>ID</th>
                <th>{t("fields.code")}</th>
                <th>{t("fields.name")}</th>
                <th>{t("fields.color")}</th>
                <th>{t("fields.widthM")}</th>
                <th>{t("fields.lengthM")}</th>
                <th>{t("fields.fabricType")}</th>
                <th>{t("fields.weave")}</th>
                <th>{t("fields.finish")}</th>
                <th>{t("fields.pricePerMeter")}</th>
                {isAdmin && <th>{t("ui.actions")}</th>}
              </tr>
            </thead>
            <tbody>
              {items.map((f) => (
                <tr key={f.id}>
                  <td>#{f.id}</td>
                  <td>
                    <b>{f.code}</b>
                  </td>
                  <td>{f.name || "-"}</td>
                  <td>{f.color || "-"}</td>
                  <td>{f.width_m ?? "-"}</td>
                  <td>{f.length_m ?? "-"}</td>
                  <td>{f.fabric_type || "-"}</td>
                  <td>{f.weave || "-"}</td>
                  <td>{f.finish || "-"}</td>
                  <td>{f.price_per_meter ?? "-"}</td>
                  {isAdmin && (
                    <td className="actions">
                      <button className="btn btn-danger" type="button" onClick={() => deleteFabric(f.id)}>
                        {t("actions.delete")}
                      </button>
                    </td>
                  )}
                </tr>
              ))}
              {items.length === 0 && (
                <tr>
                  <td colSpan={isAdmin ? 11 : 10} style={{ color: "var(--muted)" }}>
                    {t("ui.noFabrics")}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}

